### ISSUE TITLE
Can  grease pencil-addon achieve motion blur?😊

### ISSUE THREAD

**Issue by infernoshoot** [Pullusb/greasepencil-addon#21]
Can  grease pencil-addon achieve motion blur?😊

**Comment by Pullusb** [comment]
TL;DR: No.

Since drawing are different strokes at each frames you can't calculate motion vector between them.
And even if made possible by faking it somehow, motion blur is determined in the render engine, not related to any plugin.

Depending on how you made you're drawing, there might be a way to fake it, but it'll be with dedicated standalone apps that add motion blur as a post effect by analyzing the frame of a video you exported from Blender.

Cheers
