### ISSUE TITLE
Camera Mirror Flip - unable to assign shortcut

### ISSUE THREAD

**Issue by NeighNeighNeigh** [Pullusb/greasepencil-addon#22]
Is it just me, or is it currently impossible to assign a shortcut to the **Camera Mirror Flip** command? I can't find it in the keymap editor, nor does right clicking reveal an "assign shortcut" button. I'd really like to put this command on my macropad.

Sorry I forgot to include version information:

OS: macOS Monterey Version 12.6
Blender version: Version 3.3.0 (3.3.0 2022-09-07)
Addon version: 1.6.1

**Comment by Pullusb** [comment]
Hi ! I realize I never answered your issue and I apologize.

You can either create a keymap yourself using the id `gp.camera_flip_x`

Otherwise you can also install `GP toolbox` it has the exact same feature (amidst a LOT of feature 😉), and you can assign shortcut on this one.

For the next version of Blender (3.6 now ^^') I'll exposed it to the "assign shortcut"
